 const data = [
	{
		id:"1",
		name:"KVIV Residence",
		address:"953 Marquardt Tunnel",
		city:"new york",
		image:"images/1.jpg",
		price:12000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	{
		id:"2",
		name:"Carter Ramp",
		address:"09278 Bergnaum Underpass",
		city:"paris",
		image:"images/2.jpg",
		price:10000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"3",
		name:"3985 Smitham Avenue",
		address:"7070 Smith Summit",
		city:"new york",
		image:"images/3.jpg",
		price:19000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"4",
		name:"Botsford Gardens",
		address:"69, Kirti Society",
		city:"mumbai",
		image:"images/4.jpg",
		price:8000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	{
		id:"5",
		name:" Kara Street",
		address:"23, Bishnu Apartments",
		city:"mumbai",
		image:"images/5.jpg",
		price:12000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"6",
		name:"Kunze Green",
		address:"21437 Hills Freeway Suite 872",
		city:"paris",
		image:"images/6.jpg",
		price:15000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"7",
		name:"Spencer Roads",
		address:"578 Manley Forks Apt. 943",
		city:"london",
		image:"images/7.jpg",
		price:12000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	{
		id:"8",
		name:"Cruickshank Alleyway",
		address:"Apt. 450 777 Douglas Grange",
		city:"new york",
		image:"images/1.jpg",
		price:7000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"9",
		name:"Krystel Highway",
		address:"405 Boyer Towers",
		city:"london",
		image:"images/1.jpg",
		price:5000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	{
		id:"10",
		name:"KVIV Residence",
		address:"953 Marquardt Tunnel",
		city:"new york",
		image:"images/1.jpg",
		price:12000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	{
		id:"11",
		name:"Carter Ramp",
		address:"09278 Bergnaum Underpass",
		city:"paris",
		image:"images/2.jpg",
		price:10000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"12",
		name:"3985 Smitham Avenue",
		address:"7070 Smith Summit",
		city:"new york",
		image:"images/3.jpg",
		price:19000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"13",
		name:"Botsford Gardens",
		address:"69, Kirti Society",
		city:"mumbai",
		image:"images/4.jpg",
		price:8000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	{
		id:"14",
		name:" Kara Street",
		address:"23, Bishnu Apartments",
		city:"mumbai",
		image:"images/5.jpg",
		price:12000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"15",
		name:"Kunze Green",
		address:"21437 Hills Freeway Suite 872",
		city:"paris",
		image:"images/6.jpg",
		price:15000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"16",
		name:"Spencer Roads",
		address:"578 Manley Forks Apt. 943",
		city:"london",
		image:"images/7.jpg",
		price:12000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	{
		id:"17",
		name:"Cruickshank Alleyway",
		address:"Apt. 450 777 Douglas Grange",
		city:"new york",
		image:"images/1.jpg",
		price:7000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"18",
		name:"Krystel Highway",
		address:"405 Boyer Towers",
		city:"london",
		image:"images/1.jpg",
		price:5000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	{
		id:"19",
		name:"KVIV Residence",
		address:"953 Marquardt Tunnel",
		city:"new york",
		image:"images/1.jpg",
		price:12000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	{
		id:"20",
		name:"Carter Ramp",
		address:"09278 Bergnaum Underpass",
		city:"paris",
		image:"images/2.jpg",
		price:10000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"21",
		name:"3985 Smitham Avenue",
		address:"7070 Smith Summit",
		city:"new york",
		image:"images/3.jpg",
		price:19000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"22",
		name:"Botsford Gardens",
		address:"69, Kirti Society",
		city:"mumbai",
		image:"images/4.jpg",
		price:8000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	{
		id:"23",
		name:" Kara Street",
		address:"23, Bishnu Apartments",
		city:"mumbai",
		image:"images/5.jpg",
		price:12000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"24",
		name:"Kunze Green",
		address:"21437 Hills Freeway Suite 872",
		city:"paris",
		image:"images/6.jpg",
		price:15000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"25",
		name:"Spencer Roads",
		address:"578 Manley Forks Apt. 943",
		city:"london",
		image:"images/7.jpg",
		price:12000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	{
		id:"26",
		name:"Cruickshank Alleyway",
		address:"Apt. 450 777 Douglas Grange",
		city:"new york",
		image:"images/1.jpg",
		price:7000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:true
	},
	{
		id:"27",
		name:"Krystel Highway",
		address:"405 Boyer Towers",
		city:"london",
		image:"images/1.jpg",
		price:5000,
		bed_count: 2,
		rooms: 3,
		bathroom: 2,
		sqft: 1000,
		isPopular:false
	},
	
 ]

 export default data